# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true

# Mod Properties
mod_version=1.0.4
maven_group=com.kwesou
archives_base_name=press2hold

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5
fabric_version=0.161.0+26.3
loom.disableModJavadoc=true
